/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import archivos.Archivo;
import archivos.SimpleLinkedList;
import entidades.Usuario;
import java.util.LinkedList;
import javax.swing.JOptionPane;

/**
 *
 * @author Axel
 */
public class FrmLogin extends javax.swing.JFrame {
    private Archivo archivo=new Archivo();
    private SimpleLinkedList<Usuario> usuarios;
    /**
     * Creates new form loginPage
     */
    public FrmLogin() {
        initComponents();
        usuarios=archivo.read("src\\Resources\\usuarios.txt");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEntrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        txtPass = new javax.swing.JTextField();
        btnInvitado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnEntrar.setText("Entrar");
        btnEntrar.setToolTipText("");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });

        jLabel2.setText("Usuario");

        jLabel1.setText("Contraseña");

        btnInvitado.setText("Invitado");
        btnInvitado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInvitadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnInvitado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEntrar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEntrar)
                    .addComponent(btnInvitado))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        // TODO add your handling code here:
        Usuario usuario=new Usuario(txtUser.getText().toString(),txtPass.getText().toString());
        
        if(txtPass.getText().toString().trim().equals("") && txtUser.getText().toString().trim().equals("")){
            JOptionPane.showMessageDialog(this, "Introducir Usuario y Contraseña o entrar como Invitado!", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
            if(usuarios!=null && usuarios.contains(usuario)){
                Archivo archivo=new Archivo(txtUser.getText().toString());
                FrmHome frm = new FrmHome(archivo);
                frm.setLocationRelativeTo(null);
                frm.setVisible(true);
                this.setVisible(false);       
            }else{
                int flag=0;
                for(Usuario user:usuarios){
                    System.out.println();
                    if(user.getUsuario().equals(usuario.getUsuario())){
                        JOptionPane.showMessageDialog(this, "¡Contraseña incorrecta!", "Error", JOptionPane.ERROR_MESSAGE);
                        flag=1;
                        break;
                    }
                }
                if(flag!=1)
                if (JOptionPane.showConfirmDialog(null, "¿Desea crear este usuario con ese nombre y contraseña ya que no existe?",
                        "WARNING", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                    // yes option
                    Archivo archivo=new Archivo(txtUser.getText().toString());
                    if(usuarios==null){
                        usuarios=new SimpleLinkedList<>();
                    }
                    usuarios.addLast(usuario);
                    archivo.save(usuarios, "src\\Resources\\usuarios.txt");
                    FrmHome frm = new FrmHome(archivo);
                    frm.setLocationRelativeTo(null);
                    frm.setVisible(true);
                    this.setVisible(false); 
                } else {
                    // no option
                    JOptionPane.showMessageDialog(this, "Introducir Usuario y Contraseña o entrar como Invitado!", "Error", JOptionPane.ERROR_MESSAGE);
                }
            
            }
            
        }
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void btnInvitadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInvitadoActionPerformed
        // TODO add your handling code here:
        Archivo archivo=new Archivo();
        FrmHome frm = new FrmHome(archivo);
        frm.setLocationRelativeTo(null);
        frm.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_btnInvitadoActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JButton btnInvitado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtPass;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
